swaylock \
	--ignore-empty-password \
	--daemonize \
	--image ~/.config/sway/wallpaper-02.jpg \
	--hide-keyboard-layout \
	--disable-caps-lock-text \
	--indicator-idle-visible \
	--indicator-radius 130 \
	--indicator-thickness 16 \
	--key-hl-color 880033 \
	--inside-color 00000088 \
	--line-color 00000000
